Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Multi_Claims.Data;
using Multi_Claims.Models;
using Multi_Claims.ViewModels;
using System.Security.Claims;

namespace Multi_Claims.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AdministrationController(ApplicationDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            this._context = context;
            this._userManager = userManager;
            this._signInManager = signInManager;
            this._roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var users = _context.Users.ToList();

            ViewBag.Users = users;
            return View();
        }

        public async Task<IActionResult> ManageUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);    

            if(user == null)
            {
                ViewBag.ErrorMessage = $"User with Id {userId} not found.";

                return RedirectToAction("NotFound");
            }

            var existingUserClaims = await _userManager.GetClaimsAsync(user);

            var model = new UserClaimsVM
            {
                UserId = userId,
            };

            foreach(Claim claim in ClaimsStore.AllClaims)
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type,
                };

                // If the user has the claim, set IsSelected property to true, so UI will check on checkbox
                if(existingUserClaims.Any(c => c.Type == claim.Type))
                {
                    userClaim.IsSelected = true;
                }

                model.Cliams.Add(userClaim);
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageUser(UserClaimsVM model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id {model.UserId} not found.";

                return RedirectToAction("NotFound");
            }

            var claims = await _userManager.GetClaimsAsync(user);
            var result = await _userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "Can't remove user claims");
                return View(model);
            }

            result = await _userManager.AddClaimsAsync(user,
                model.Cliams.Where(c => c.IsSelected).Select(c => new Claim(c.ClaimType, c.ClaimType)));

            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "Can't remove user claims");
                return View(model);
            }

            return RedirectToAction("ManageUser", new { userId = model.UserId });
        }

        public IActionResult NotFound()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Multi_Claims.ViewModels;

namespace Multi_Claims.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public AuthController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginUserVM model/*, string? returnUrl = null*/)
        {
            //returnUrl ??= Url.Content("~/");

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if(user == null)
                {
                   ModelState.AddModelError(string.Empty, "User doesn't exist.");

                   return View(model);
                }

                //if (!string.IsNullOrEmpty(returnUrl))
                //{
                //    return LocalRedirect(returnUrl);
                //}

                await _signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterUserVM model/*, string? returnUrl = null*/)
        {
            var user = new IdentityUser { UserName = model.Username, Email = model.Email };
            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, isPersistent: false);
                //return LocalRedirect(returnUrl);
                return LocalRedirect("/");
            }

            foreach(var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout(/*string returnUrl = null*/)
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");

            //if(returnUrl != null)
            //{
            //    return LocalRedirect(returnUrl);
            //}
            //else
            //{
            //    return RedirectToAction("Login");
            //}
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Multi_Claims.Data;
using Multi_Claims.Models;

namespace Multi_Claims.Controllers
{
    public class MovieController : Controller
    {
        private readonly ApplicationDbContext context;

        public MovieController(ApplicationDbContext context)
        {
            this.context = context;
        }

        void CONFIG()
        {
            var subTitles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Khmer", Value = "Khmer" },
                new SelectListItem { Text = "English", Value = "English" },
                new SelectListItem { Text = "Japanese", Value = "Japanese" },
                new SelectListItem { Text = "Chinese", Value = "Chinese" },
            };

            var languages = new List<SelectListItem>
            {
                new SelectListItem { Text = "Khmer", Value = "Khmer" },
                new SelectListItem { Text = "English", Value = "English" },
                new SelectListItem { Text = "Japanese", Value = "Japanese" },
                new SelectListItem { Text = "Chinese", Value = "Chinese" },
            };

            ViewBag.SubTitles = subTitles;
            ViewBag.Languages = languages;
        }

        public IActionResult Index()
        {
            var movies = context.Movies.ToList();

            return View(movies);
        }

        public IActionResult Create()
        {
            CONFIG();

            return View();
        }

        [Authorize(Policy = "CreatePolicy")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Movie model)
        {
            CONFIG();

            if (ModelState.IsValid)
            {
                context.Movies.Add(model);
                context.SaveChanges();

                TempData["SuccessMsg"] = "Create movie successfully.";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            CONFIG();

            var movie = context.Movies.Find(id);

            if (movie == null || movie.MovieId == 0)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Movie model)
        {
            CONFIG();

            if (ModelState.IsValid)
            {
                context.Movies.Update(model);
                context.SaveChanges();

                TempData["SuccessMsg"] = "Create movie successfully.";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            var movie = context.Movies.Find(id);

            if (movie == null || movie.MovieId == 0)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remove(int? id)
        {
            var data = context.Movies.Find(id);

            if (data == null)
            {
                NotFound();
            }

            context.Movies.Remove(data);
            context.SaveChanges();

            TempData["SuccessMsg"] = "Remove movie successfully.";
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Multi_Claims</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Multi_Claims.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="d-flex navbar navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex justify-content-between align-items-center">
                    <a class="navbar-brand fw-bold" asp-controller="Home" asp-action="Index">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <span>
                                Hi, @User?.Identity?.Name!
                            </span>
                        }else{
                            <span>
                                Hi, Guest!
                            </span>
                        }
                    </a>
                    <ul class="d-flex flex-grow-1" style="list-style: none;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Index">Manage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <div class=" justify-content-between">
                    <ul class="d-flex"  style="list-style: none;">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-primary" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <form method="POST" asp-controller="Auth" asp-action="Logout">
                                    <input type="submit" class="nav-link text-light btn btn-danger"value="Logout" />
                                </form>
                            </li>
                        }
                        
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>